package com.example.mechanicdb.models

class DataSource {
    companion object{
        fun createDataSet(): ArrayList<Vehicle>{
            val list = ArrayList<Vehicle>()
            list.add(
                Vehicle(
                    "Ford",
                    "F-150",
                    1990,
                    25000,
                    "",
                    1,
                12345
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Mustang",
                    1965,
                    2000,
                    "",
                    2,
                    1322
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Escape",
                    2005,
                    250000,
                    "",
                    3,
                    123421125
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "F-150",
                    1990,
                    25000,
                    "",
                    1,
                    12345
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Mustang",
                    1965,
                    2000,
                    "",
                    2,
                    1322
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Escape",
                    2005,
                    250000,
                    "",
                    3,
                    123421125
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "F-150",
                    1990,
                    25000,
                    "",
                    1,
                    12345
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Mustang",
                    1965,
                    2000,
                    "",
                    2,
                    1322
                )
            )
            list.add(
                Vehicle(
                    "Ford",
                    "Escape",
                    2005,
                    250000,
                    "",
                    3,
                    123421125
                )
            )
            return list
        }

    }
}